services:
  mp3tag:
    build:
      context: .
      dockerfile: Dockerfile
    image: mp3tag-selkies:latest
    container_name: mp3tag

    ports:
      - "3001:3001"

    environment:
      TITLE: "Mp3tag"
      PIXELFLUX_WAYLAND: "true"
      RESTART_APP: "true"
      WINEDEBUG: "-all"
      PUID: "1000"
      PGID: "1000"


    volumes:
      - ./config:/config
      - ./music:/music

    shm_size: 1gb
    restart: unless-stopped
